site_name: My Docs
theme:
  name: "material"
  logo: "img/favicon.svg"
  favicon: "img/favicon.svg"
  palette:
    - primary: white
  features:
    - navigation.sections  # Sections are included in the navigation on the left.
    - toc.integrate
    - search.suggest
    - search.highlight

site_name: torch2jax
site_description: The documentation for the torch2jax package.
site_author: Robert Dyro 
site_url: https://rdyro.github.io/torch2jax/

repo_url: https://github.com/rdyro/torch2jax/
repo_name: rdyro/torch2jax

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
          python:
              options:
                  inherited_members: true
                  show_root_heading: true
                  show_if_no_docstring: true
                  show_signature_annotations: false
                  heading_level: 0
                  members_order: source

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - mdx_truly_sane_lists
  - pymdownx.tasklist


nav:
    - Overview: 'index.md'
    - Installation: 'installation.md'
    - Roadmap: 'roadmap.md'
    - Changelog: 'changelog.md'
    - Examples:
      - BERT: 'examples/bert_example.md'
      - ResNet: 'examples/resnet_example.md'
      - Data Parallel: 'examples/data_parallel.md'
    - Full API:
        - torch2jax: 'api/torch2jax.md'
        - torch2jax_with_vjp: 'api/torch2jax_with_vjp.md'
        - utils: 'api/utils.md'
